CREATE TABLE [dbo].[Card]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CsId] INT NOT NULL, 
    [Name] VARCHAR(200) NOT NULL, 
    [MtgJsonId] VARCHAR(100) NOT NULL, 
    [ScryfallId] VARCHAR(100) NOT NULL, 
    [MtgJsonCode] VARCHAR(10) NOT NULL 
)
